#!/usr/bin/env python3
"""Generates src/unicode_tables.inc from Python's Unicode database.

Usage: python3 tools/gen_unicode_tables.py > src/unicode_tables.inc

The tables hold the codepoint ranges of the general categories L (letter) and
N (number), which the pre-tokenizer regexes are written in terms of.
"""

import sys
import unicodedata


def ranges(first_letter):
    out = []
    start = None
    for cp in range(0x110000):
        inside = unicodedata.category(chr(cp))[0] == first_letter
        if inside and start is None:
            start = cp
        elif not inside and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def emit(name, table):
    print(f"inline constexpr CodepointRange {name}[] = {{")
    for i in range(0, len(table), 6):
        row = ", ".join(f"{{0x{a:X}, 0x{b:X}}}" for a, b in table[i : i + 6])
        print(f"    {row},")
    print("};\n")


def main():
    print(f"// Generated by tools/gen_unicode_tables.py from Unicode {unicodedata.unidata_version}. Do not edit.\n")
    emit("kLetterRanges", ranges("L"))
    emit("kNumberRanges", ranges("N"))


if __name__ == "__main__":
    sys.exit(main())
